### ISSUE TITLE
 The fig file in folder "SmallScreenUI" is not right.

### ISSUE THREAD

**Issue by weili1457355863** [Teoge/MarkToolForParkingLotPoint#3]
Please change the new fig file. Thank you very much.

**Comment by Teoge** [comment]
It works perfectly fine on my computer. Could you describe your problem in detail?

**Comment by weili1457355863** [comment]
Thanks for your response. The "main.fig" in the SmallScreenUI folder is wrong (It is for the ps2.0). I have changed it according to your big "main.fig". 
Link:https://pan.baidu.com/s/15RzmH0uDxcYeBOaD1nSmkw 
Code：55q1

**Comment by Teoge** [comment]
Oh, you are talking about the gui in the directional_point branch. Yes, that one is totally out-of-date. I will update it when I have time.

**Comment by Teoge** [comment]
I have updated the small screen UI. It should be fine now.
